services:
  db:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      PG_URL: postgres://user1:123456@0.0.0.0:5432/postgres
      POSTGRES_USER: userL0
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
      APP_VERSION: 0.0.1
      DB_TYPE: postgres
      DB_SERVER: localhost
      DB_PORT: 5432
      DB_NAME: L0-db
      DB_SCHEME: public
      DB_USER: postgres
      DB_PASSWORD: 123456
  nats-streaming:
    image: 'nats-streaming:latest'
    entrypoint:
      - /nats-streaming-server
      - -cid
      - main_cluster
    ports:
      - 127.0.0.1:4222:4222
    restart: always
    tty: true
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'

